DROP TABLE FUNCIONARIOS.APP_TEST;
DROP SCHEMA FUNCIONARIOS;
CREATE SCHEMA FUNCIONARIOS;

CREATE TABLE FUNCIONARIOS.APP_TEST (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(15),
    SOBRENOME VARCHAR(30),
    IDADE INT,
    CPF BIGINT UNIQUE
);

INSERT INTO FUNCIONARIOS.APP_TEST (NOME, SOBRENOME, IDADE, CPF) VALUES ('Marllon', 'Zucolotto', 24, 41234567895);
INSERT INTO FUNCIONARIOS.APP_TEST (NOME, SOBRENOME, IDADE, CPF) VALUES ('Brenda', 'Zucolotto', 31, 31234567895);

UPDATE FUNCIONARIOS.APP_TEST SET SOBRENOME = 'Bentes' WHERE SOBRENOME = 'Zucolotto' AND NOME = 'Brenda';

DELETE FROM FUNCIONARIOS.APP_TEST WHERE ID = 1;

SELECT * FROM FUNCIONARIOS.APP_TEST;

